name: Deploy CocoaPod Trunk

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        # For info on how to obtain a new token see
        # https://medium.com/swlh/automated-cocoapod-releases-with-github-actions-8526dd4535c7
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push FireworkVideo.podspec
